name: Markdown Lint

on:
    push:
        branches:
            - dev

jobs:
    markdown-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Lint markdown
              uses: DavidAnson/markdownlint-cli2-action@v16
              with:
                config: 'config/.markdownlint.yml'
                globs: 'readme.md'