name: Markdown Lint

on:
    push:
        branches:
            - dev

jobs:
    markdown-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Copy markdown config file to root
              run: |
                cp ./.github/workflows/.markdownlint.yml .markdownlint.yml
            - name: Lint markdown
              uses: avto-dev/markdown-lint@v1
              with:
                rules: '.github/workflows/.markdownlint.yml'
                args: "readme.md"
                # args: "**/*.md" # Linting all markdown files