---
name: housekeeping

on:
    push:
        branches:
            - dev

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Check out the code
            
            - uses: actions/setup-node@v1
              name: Run spell check
              with:
                node-version: "12"

            - run: npm install -g cspell
            - run: cspell --config ./config/cSpell.json --no-progress "**/*.md"
