---
name: housekeeping

on:
    push:
        branches:
            - dev

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Check out the code
            
            - uses: actions/setup-node@v1
              name: Set up node
              with:
                node-version: "20"

            - run: npm install -g cspell@latest
              name: Install cspell@latest

            - run: cspell --config ./config/cSpell.json --no-progress "**/*.md"
              name: Run cSpell
